# the filter currently checks for words that are 3 or more characters.
---
ass: "*ss"
asses: "*ss*s"
asshole: "*ssh*l*"
arsehole: "*rs*h*l*"
assholes: "*ssh*l*s"
anal: "*n*l"
bastard: b*st*rd
beastial: b**st**l
beastiality: b**st**l*ty
beastility: b**st*l*ty
bestial: b*st**l
bestiality: b*st**l*ty
bitch: b*tch
bitcher: b*tch*r
bitchers: b*tch*rs
bitches: b*tch*s
bitchin: b*tch*n
bitching: b*tch*ng
blowjob: bl*wj*b
blowjobs: bl*wj*bs
boner: b*ner
bullshit: b*llsh*t
butthole: b*tth*l*
cameltoe: c*m*lt**
clit: cl*t
cock: c*ck
cocks: c*cks
cocksuck: c*cks*ck
cocksucked: c*cks*ck*d
cocksucker: c*cks*ck*r
cocksucking: c*cks*ck*ng
cocksucks: c*cks*cks
cum: c*m
cummer: c*mm*r
cumming: c*mm*ng
cums: c*ms
cumshot: c*msh*t
cunillingus: c*n*ll*ng*s
cunnilingus: c*nn*l*ng*s
cunt: c*nt
cuntlick: c*ntl*ck
cuntlicker: c*ntl*ck*r
cuntlicking: c*ntl*ck*ng
cunts: c*nts
cyberfuc: cyb*rf*c
cyberfuck: cyb*rf*ck
cyberfucked: cyb*rf*ck*d
cyberfucker: cyb*rf*ck*r
cyberfuckers: cyb*rf*ck*rs
cyberfucking: cyb*rf*ck*ng
dildo: d*ld*
dildos: d*ld*s
dick: d*ck
dink: d*nk
dinks: d*nks
dyke: dy*e
ejaculate: "*j*c*l*t*"
ejaculated: "*j*c*l*t*d"
ejaculates: "*j*c*l*t*s"
ejaculating: "*j*c*l*t*ng"
ejaculatings: "*j*c*l*t*ngs"
ejaculation: "*j*c*l*t**n"
erection: er*ct**n
erotic: "*r*t*c"
erotism: "*r*t*sm"
fag: f*g
fagging: f*gg*ng
faggot: f*gg*t
faggs: f*ggs
fagot: f*g*t
fagots: f*g*ts
fags: f*gs
fart: f*rt
farted: f*rt*d
farting: f*rt*ng
fartings: f*rt*ngs
farts: f*rts
farty: f*rty
felatio: f*l*t**
fellatio: f*ll*t**
fingerfuck: f*ng*rf*ck
fingerfucked: f*ng*rf*ck*d
fingerfucker: f*ng*rf*ck*r
fingerfuckers: f*ng*rf*ck*rs
fingerfucking: f*ng*rf*ck*ng
fingerfucks: f*ng*rf*cks
fistfuck: f*stf*ck
fistfucked: f*stf*ck*d
fistfucker: f*stf*ck*r
fistfuckers: f*stf*ck*rs
fistfucking: f*stf*ck*ng
fistfuckings: f*stf*ck*ngs
fistfucks: f*stf*cks
fuck: f*ck
fucked: f*ck*d
fucker: f*ck*r
fuckers: f*ck*rs
fuckin: f*ck*n
fucking: f*ck*ng
fuckings: f*ck*ngs
fuckme: f*ckm*
fucks: f*cks
fuk: f*k
fuks: f*ks
gangbang: g*ngb*ng
gangbanged: g*ngb*ng*d
gangbangs: g*ngb*ngs
gaysex: g*ys*x
goddamn: g*dd*mn
homoerotic: h*m**r*t*c
hardcoresex: h*rdc*r*s*x
horniest: h*rn**st
horny: h*rny
hotsex: h*ts*x
incest: "*nc*st"
jism: j*sm
jiz: j*z
jizm: j*zm
kock: k*ck
kondum: k*nd*m
kondums: k*nd*ms
kum: k*m
kumer: k*mm*r
kummer: k*mm*r
kumming: k*mm*ng
kums: k*ms
kunilingus: k*n*l*ng*s
lust: l*st
lusting: l*st*ng
muff: m*ff
masturbate: m*st*rb*t*
masterbate: m*st*rb*t*
masturbation: m*st*rb*t**n
mothafuck: m*th*f*ck
mothafucka: m*th*f*ck*
mothafuckas: m*th*f*ck*s
mothafuckaz: m*th*f*ck*z
mothafucked: m*th*f*ck*d
mothafucker: m*th*f*ck*r
mothafuckers: m*th*f*ck*rs
mothafuckin: m*th*f*ck*n
mothafucking: m*th*f*ck*ng
mothafuckings: m*th*f*ck*ngs
mothafucks: m*th*f*cks
motherfuck: m*th*rf*ck
motherfucked: m*th*rf*ck*d
motherfucker: m*th*rf*ck*r
motherfuckers: m*th*rf*ck*rs
motherfuckin: m*th*rf*ck*n
motherfucking: m*th*rf*ck*ng
motherfuckings: m*th*rf*ck*ngs
motherfucks: m*th*rf*cks
nigga: n*gg*
niger: n*gg*r
nigger: n*gg*r
niggers: n*gg*rs
nipples: n*ppl*s
orgasim: "*rg*s*m"
orgasims: "*rg*s*ms"
orgasm: "*rg*sm"
orgasms: "*rg*sms"
panty: p*nty
pedophile: p*d*ph*le
pedo: p*d*
penis: p*n*s
phonesex: ph*n*s*x
phuk: ph*k
phuked: ph*k*d
phuking: ph*k*ng
phukked: ph*kk*d
phukking: ph*kk*ng
phuks: ph*ks
phuq: ph*q
pis: p*ss
piss: p*ss
pisser: p*ss*r
pissed: p*ss*d
pisser: p*ss*r
pissers: p*ss*rs
pises: p*ss*s
pisses: p*ss*s
pisin: p*ss*n
pissin: p*ss*n
pising: p*ss*ng
pissing: p*ss*ng
pisof: p*ss*ff
pissoff: p*ss*ff
porn: p*rn
porno: p*rn*
pornography: p*rn*gr*phy
pornos: p*rn*s
preteen: pr*t**n
prick: pr*ck
pricks: pr*cks
pussies: p*ss**s
pusies: p*ss**s
pussy: p*ssy
pusy: p*ssy
pussys: p*ssys
pusys: p*ssys
rape: r*p*
raping: r*p*ng
rapist: r*p*st
retard: r*t*rd
rimming: r*mm*ng
rimjob: r*mj*b
scissoring: sc*ss*r*ng
schlong: schl*ng
semen: s*m*n
shit: sh*t
shited: sh*t*d
shitfull: sh*tf*ll
shiting: sh*t*ng
shitings: sh*t*ngs
shits: sh*ts
shitted: sh*tt*d
shitter: sh*tt*r
shitters: sh*tt*rs
shitting: sh*tt*ng
shittings: sh*tt*ngs
shitty: sh*tty
shity: sh*tty
slit: sl*t
slut: sl*t
sluts: sl*ts
slutty: sl*tty
smut: sm*t
sodomy: s*d*m*
sodomize: s*d*m*z*
sodomise: s*d*m*s*
spunk: sp*nk
spunk: sp*nk
suicide: s**c*de
tranny: tr*nny
transexual: tr*ns*x**l
tits: t*ts
titties: t*tt**s
twat: tw*t
upskirt: "*psk*rt"
vagina: v*g*n*
vibrator: v*br*t*r
wank: w*nk
wanker: w*nk*r
whore: wh*r*
